name: Schedule Multiple POST Requests

on:
  schedule:
    - cron: "*/20 * * * *"  # Every hour

jobs:
  send_requests:
    runs-on: ubuntu-latest
    steps:
    # First POST request
    - name: Send Booking POST Request
      run: |
        curl -X POST https://booking-control-main.azurewebsites.net/api/orchestrators/orchestrator_function?code=J82lgyhMTvskocmBo3beA1IMxtVKZ0LPlxnVBXYUie8DAzFuDTSCrw== \
        -H "Content-Type: application/json" \
        -d '{"value": [{"subscriptionId": "926d8d5d-f280-4926-8ca9-747ab202a993", "clientState": "Booking Subscription Sharepoint", "expirationDateTime": "2024-05-29T22:27:54.0000000Z", "resource": "671cf819-47f1-41dc-9997-6aaae01597cb", "tenantId": "ebe72cdd-e4da-4cec-8ca7-641cafe9b33a", "siteUrl": "/sites/azure-storage", "webId": "3fcae0a6-2cb9-41d6-b54d-a2c638d57929"}]}'
    
    # # Second POST request
    # - name: Send Update POST Request
    #   run: |
    #     curl -X POST https://booking-control-main.azurewebsites.net/api/orchestrators/orchestrator_function?code=J82lgyhMTvskocmBo3beA1IMxtVKZ0LPlxnVBXYUie8DAzFuDTSCrw== \
    #     -H "Content-Type: application/json" \
    #     -d '{"key3": "value3", "key4": "value4"}'
    
    # # Third POST request
    # - name: Send Cancel POST Request
    #   run: |
    #     curl -X POST https://booking-control-main.azurewebsites.net/api/orchestrators/orchestrator_function?code=J82lgyhMTvskocmBo3beA1IMxtVKZ0LPlxnVBXYUie8DAzFuDTSCrw== \
    #     -H "Content-Type: application/json" \
    #     -d '{"key5": "value5", "key6": "value6"}'
